In [99]:
%matplotlib inline

from collections import defaultdict
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import json

In [23]:
def load_dataset(tournament='World_Cup'):
    matches, events = {}, {}
    matches = json.load(open('./data/matches/matches_{}.json'.format(tournament)))
    events = json.load(open('./data/events/events_{}.json'.format(tournament)))
    return matches, events

def get_match(matches, events):
    match_id2events = defaultdict(list)
    match_id2match = defaultdict(dict)
    for event in events:
        match_id = event['matchId']
        match_id2events[match_id].append(event)
                                         
    for match in matches:
        match_id = match['wyId']
        match_id2match[match_id] = match
    
    return match_id2events, match_id2match
    
def get_player():
    players = json.load(open('./data/players.json'))
    player_id2player = defaultdict(dict)
    for player in players:
        player_id = player['wyId']
        player_id2player[player_id] = player
    return player_id2player
        
def get_competitions():
    competitions = json.load(open('./data/competitions.json'))
    competition_id2competition = defaultdict(dict)
    for competition in competitions:
        competition_id = competition['wyId']
        competition_id2competition[competition_id] = competition
    return competition_id2competition

def get_teams():
    teams = json.load(open('./data/teams.json'))
    team_id2team = defaultdict(dict)
    for team in teams:
        team_id = team['wyId']
        team_id2team[team_id] = team
    return team_id2team

In [24]:
matches, events = load_dataset()
match_id2events, match_id2match = get_match(matches, events)
player_id2player = get_player()
competition_id2competition = get_competitions()
team_id2team = get_teams()

In [39]:
event_key = []
sub_event_key = []

for events in match_id2events.values():
    for event in events:
        event_key.append(event['eventName'])
        sub_event_key.append(event['subEventName'])
        
event_key = list(set(event_key))
sub_event_key = list(set(sub_event_key))

In [25]:
team_id2team[4418]

{'city': 'Paris',
 'name': 'France',
 'wyId': 4418,
 'officialName': 'France',
 'area': {'name': 'France',
  'id': 250,
  'alpha3code': 'FRA',
  'alpha2code': 'FR'},
 'type': 'national'}

In [52]:
event_stats = []
sub_event_stats = []
teamid = 4418

for match in match_id2match.values():
    for team in match['teamsData'].values():
        if team['teamId'] == teamid:
            print(match['label'])
            events = match_id2events[match['wyId']]
            event_stat = {key: 0 for key in event_key}
            sub_event_stat = {key: 0 for key in sub_event_key}

            for event in events:
                if event['teamId'] == teamid:
                    event_stat[event['eventName']] += 1
                    sub_event_stat[event['subEventName']] += 1

            event_stats.append(event_stat)
            sub_event_stats.append(sub_event_stat)

France - Croatia, 4 - 2
France - Belgium, 1 - 0
Uruguay - France, 0 - 2
France - Argentina, 4 - 3
Denmark - France, 0 - 0
France - Peru, 1 - 0
France - Australia, 2 - 1

In [55]:
event_stats[0]

{'Save attempt': 3,
 'Offside': 1,
 'Shot': 7,
 'Goalkeeper leaving line': 5,
 'Others on the ball': 86,
 'Free Kick': 51,
 'Pass': 241,
 'Duel': 194,
 'Foul': 13}

In [56]:
sub_event_stats[0]

{'Cross': 2,
 '': 1,
 'Touch': 59,
 'Hand pass': 2,
 'Shot': 7,
 'Head pass': 32,
 'Free Kick': 9,
 'Acceleration': 6,
 'Smart pass': 6,
 'Violent Foul': 0,
 'Clearance': 21,
 'Time lost foul': 0,
 'Out of game foul': 0,
 'High pass': 18,
 'Simulation': 0,
 'Throw in': 22,
 'Goal kick': 15,
 'Launch': 16,
 'Goalkeeper leaving line': 5,
 'Reflexes': 3,
 'Air duel': 41,
 'Penalty': 1,
 'Foul': 12,
 'Protest': 0,
 'Ground defending duel': 51,
 'Save attempt': 0,
 'Simple pass': 165,
 'Hand foul': 1,
 'Ground loose ball duel': 29,
 'Free kick shot': 0,
 'Free kick cross': 2,
 'Ground attacking duel': 73,
 'Corner': 2,
 'Late card foul': 0}

In [84]:
team_stats = defaultdict(list)

for match in match_id2match.values():
    for team in match['teamsData'].values():
        events = match_id2events[match['wyId']]
        event_stat = {key: 0 for key in event_key}
        sub_event_stat = {key: 0 for key in sub_event_key}

        for event in events:
            if event['teamId'] == team['teamId']:
                event_stat[event['eventName']] += 1
                sub_event_stat[event['subEventName']] += 1
        try:
            event_stat['played'] += 1
        except:
            event_stat['played'] = 1

#             event_stats.append(event_stat)
#             sub_event_stats.append(sub_event_stat)

        try:
            team_stats[team['teamId']] = {k: team_stats[team['teamId']][k] + event_stat[k] for k in event_stat}
        except:
            team_stats[team['teamId']] = event_stat

In [87]:
team_stats

defaultdict(list,
            {9598: {'Save attempt': 39,
              'Offside': 11,
              'Shot': 103,
              'Goalkeeper leaving line': 20,
              'Others on the ball': 577,
              'Free Kick': 392,
              'Pass': 3708,
              'Duel': 1601,
              'Foul': 114,
              'played': 7},
             4418: {'Save attempt': 17,
              'Offside': 3,
              'Shot': 68,
              'Goalkeeper leaving line': 8,
              'Others on the ball': 479,
              'Free Kick': 324,
              'Pass': 2931,
              'Duel': 1400,
              'Foul': 97,
              'played': 7},
             2413: {'Save attempt': 28,
              'Offside': 15,
              'Shot': 77,
              'Goalkeeper leaving line': 7,
              'Others on the ball': 458,
              'Free Kick': 364,
              'Pass': 3631,
              'Duel': 1301,
              'Foul': 73,
              'played': 7},
             5629: {'Save attempt': 35,
              'Offside': 9,
              'Shot': 98,
              'Goalkeeper leaving line': 11,
              'Others on the ball': 496,
              'Free Kick': 293,
              'Pass': 3492,
              'Duel': 1192,
              'Foul': 100,
              'played': 7},
             14358: {'Save attempt': 32,
              'Offside': 7,
              'Shot': 42,
              'Goalkeeper leaving line': 3,
              'Others on the ball': 425,
              'Free Kick': 259,
              'Pass': 1647,
              'Duel': 1166,
              'Foul': 95,
              'played': 5},
             7047: {'Save attempt': 15,
              'Offside': 6,
              'Shot': 47,
              'Goalkeeper leaving line': 10,
              'Others on the ball': 359,
              'Free Kick': 235,
              'Pass': 1418,
              'Duel': 912,
              'Foul': 67,
              'played': 5},
             6380: {'Save attempt': 9,
              'Offside': 9,
              'Shot': 95,
              'Goalkeeper leaving line': 8,
              'Others on the ball': 429,
              'Free Kick': 220,
              'Pass': 2677,
              'Duel': 1057,
              'Foul': 52,
              'played': 5},
             15670: {'Save attempt': 13,
              'Offside': 2,
              'Shot': 51,
              'Goalkeeper leaving line': 15,
              'Others on the ball': 363,
              'Free Kick': 224,
              'Pass': 2060,
              'Duel': 1063,
              'Foul': 64,
              'played': 5},
             12430: {'Save attempt': 19,
              'Offside': 6,
              'Shot': 35,
              'Goalkeeper leaving line': 9,
              'Others on the ball': 251,
              'Free Kick': 205,
              'Pass': 1772,
              'Duel': 926,
              'Foul': 64,
              'played': 4},
             6697: {'Save attempt': 18,
              'Offside': 4,
              'Shot': 51,
              'Goalkeeper leaving line': 2,
              'Others on the ball': 278,
              'Free Kick': 200,
              'Pass': 2019,
              'Duel': 810,
              'Foul': 54,
              'played': 4},
             12913: {'Save attempt': 20,
              'Offside': 5,
              'Shot': 36,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 273,
              'Free Kick': 158,
              'Pass': 1958,
              'Duel': 754,
              'Foul': 38,
              'played': 4},
             15473: {'Save attempt': 33,
              'Offside': 5,
              'Shot': 52,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 363,
              'Free Kick': 187,
              'Pass': 1575,
              'Duel': 784,
              'Foul': 57,
              'played': 4},
             7712: {'Save attempt': 27,
              'Offside': 5,
              'Shot': 38,
              'Goalkeeper leaving line': 7,
              'Others on the ball': 286,
              'Free Kick': 189,
              'Pass': 1568,
              'Duel': 870,
              'Foul': 55,
              'played': 4},
             1598: {'Save attempt': 11,
              'Offside': 6,
              'Shot': 60,
              'Goalkeeper leaving line': 2,
              'Others on the ball': 283,
              'Free Kick': 205,
              'Pass': 3291,
              'Duel': 757,
              'Foul': 34,
              'played': 4},
             9905: {'Save attempt': 14,
              'Offside': 4,
              'Shot': 41,
              'Goalkeeper leaving line': 8,
              'Others on the ball': 292,
              'Free Kick': 184,
              'Pass': 1828,
              'Duel': 861,
              'Foul': 57,
              'played': 4},
             12274: {'Save attempt': 14,
              'Offside': 6,
              'Shot': 47,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 296,
              'Free Kick': 209,
              'Pass': 2251,
              'Duel': 848,
              'Foul': 59,
              'played': 4},
             17929: {'Save attempt': 20,
              'Offside': 6,
              'Shot': 20,
              'Goalkeeper leaving line': 2,
              'Others on the ball': 149,
              'Free Kick': 121,
              'Pass': 954,
              'Duel': 478,
              'Foul': 52,
              'played': 3},
             16276: {'Save attempt': 25,
              'Offside': 6,
              'Shot': 32,
              'Goalkeeper leaving line': 3,
              'Others on the ball': 193,
              'Free Kick': 134,
              'Pass': 1340,
              'Duel': 517,
              'Foul': 46,
              'played': 3},
             13869: {'Save attempt': 10,
              'Offside': 5,
              'Shot': 26,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 183,
              'Free Kick': 130,
              'Pass': 1373,
              'Duel': 596,
              'Foul': 29,
              'played': 3},
             19314: {'Save attempt': 9,
              'Offside': 10,
              'Shot': 24,
              'Goalkeeper leaving line': 7,
              'Others on the ball': 205,
              'Free Kick': 127,
              'Pass': 937,
              'Duel': 600,
              'Foul': 45,
              'played': 3},
             17322: {'Save attempt': 14,
              'Offside': 5,
              'Shot': 30,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 246,
              'Free Kick': 128,
              'Pass': 1081,
              'Duel': 702,
              'Foul': 46,
              'played': 3},
             16871: {'Save attempt': 16,
              'Offside': 5,
              'Shot': 26,
              'Goalkeeper leaving line': 11,
              'Others on the ball': 207,
              'Free Kick': 123,
              'Pass': 1024,
              'Duel': 646,
              'Foul': 45,
              'played': 3},
             3148: {'Save attempt': 14,
              'Offside': 7,
              'Shot': 65,
              'Goalkeeper leaving line': 1,
              'Others on the ball': 314,
              'Free Kick': 152,
              'Pass': 1936,
              'Duel': 505,
              'Foul': 29,
              'played': 3},
             14855: {'Save attempt': 14,
              'Offside': 0,
              'Shot': 31,
              'Goalkeeper leaving line': 13,
              'Others on the ball': 249,
              'Free Kick': 125,
              'Pass': 886,
              'Duel': 594,
              'Foul': 62,
              'played': 3},
             16823: {'Save attempt': 10,
              'Offside': 2,
              'Shot': 35,
              'Goalkeeper leaving line': 6,
              'Others on the ball': 192,
              'Free Kick': 136,
              'Pass': 1079,
              'Duel': 701,
              'Foul': 45,
              'played': 3},
             7839: {'Save attempt': 14,
              'Offside': 0,
              'Shot': 30,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 195,
              'Free Kick': 126,
              'Pass': 754,
              'Duel': 632,
              'Foul': 36,
              'played': 3},
             8493: {'Save attempt': 14,
              'Offside': 3,
              'Shot': 25,
              'Goalkeeper leaving line': 2,
              'Others on the ball': 158,
              'Free Kick': 136,
              'Pass': 1410,
              'Duel': 600,
              'Foul': 36,
              'played': 3},
             15594: {'Save attempt': 9,
              'Offside': 7,
              'Shot': 27,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 224,
              'Free Kick': 140,
              'Pass': 1278,
              'Duel': 672,
              'Foul': 37,
              'played': 3},
             16216: {'Save attempt': 9,
              'Offside': 2,
              'Shot': 34,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 226,
              'Free Kick': 132,
              'Pass': 1107,
              'Duel': 637,
              'Foul': 64,
              'played': 3},
             10840: {'Save attempt': 10,
              'Offside': 3,
              'Shot': 15,
              'Goalkeeper leaving line': 11,
              'Others on the ball': 195,
              'Free Kick': 132,
              'Pass': 587,
              'Duel': 567,
              'Foul': 46,
              'played': 3},
             16521: {'Save attempt': 12,
              'Offside': 4,
              'Shot': 32,
              'Goalkeeper leaving line': 4,
              'Others on the ball': 227,
              'Free Kick': 142,
              'Pass': 1701,
              'Duel': 573,
              'Foul': 30,
              'played': 3},
             16129: {'Save attempt': 16,
              'Offside': 4,
              'Shot': 26,
              'Goalkeeper leaving line': 10,
              'Others on the ball': 211,
              'Free Kick': 132,
              'Pass': 1184,
              'Duel': 605,
              'Foul': 38,
              'played': 3},
             0: []})

In [134]:
data = []
for idx in team_stats:
#     print(team_id2team[idx]['name'], team_stats[idx])
    column = []
    try:
        column.append(team_id2team[idx]['name'])
        for key in team_stats[idx].keys():
            column.append(team_stats[idx][key])
        data.append(column)
    except:
        pass

In [135]:
keys = []
keys.append('Team')
for key in team_stats[10840].keys():
    keys.append(key)

In [136]:
keys

['Team',
 'Save attempt',
 'Offside',
 'Shot',
 'Goalkeeper leaving line',
 'Others on the ball',
 'Free Kick',
 'Pass',
 'Duel',
 'Foul',
 'played']

In [142]:
df = pd.DataFrame(data, columns=keys)
df.set_index('Team', inplace=True)

In [143]:
df.sort_values('Shot')

,Save attempt,Offside,Shot,Goalkeeper leaving line,Others on the ball,Free Kick,Pass,Duel,Foul,played
Team,,,,,,,,,,
Iran,10,3,15,11,195,132,587,567,46,3
Panama,20,6,20,2,149,121,954,478,52,3
Senegal,9,10,24,7,205,127,937,600,45,3
Australia,14,3,25,2,158,136,1410,600,36,3
Costa Rica,16,5,26,11,207,123,1024,646,45,3
Poland,10,5,26,4,183,130,1373,596,29,3
Egypt,16,4,26,10,211,132,1184,605,38,3
Peru,9,7,27,4,224,140,1278,672,37,3
Serbia,14,5,30,4,246,128,1081,702,46,3
Iceland,14,0,30,4,195,126,754,632,36,3
Korea Republic,14,0,31,13,249,125,886,594,62,3
Saudi Arabia,12,4,32,4,227,142,1701,573,30,3
Tunisia,25,6,32,3,193,134,1340,517,46,3
Morocco,9,2,34,4,226,132,1107,637,64,3
Nigeria,10,2,35,6,192,136,1079,701,45,3
Colombia,19,6,35,9,251,205,1772,926,64,4
Japan,20,5,36,4,273,158,1958,754,38,4
Denmark,27,5,38,7,286,189,1568,870,55,4
Portugal,14,4,41,8,292,184,1828,861,57,4
Russia,32,7,42,3,425,259,1647,1166,95,5
Argentina,14,6,47,4,296,209,2251,848,59,4
Sweden,15,6,47,10,359,235,1418,912,67,5
Switzerland,18,4,51,2,278,200,2019,810,54,4
Uruguay,13,2,51,15,363,224,2060,1063,64,5
Mexico,33,5,52,4,363,187,1575,784,57,4
Spain,11,6,60,2,283,205,3291,757,34,4
Germany,14,7,65,1,314,152,1936,505,29,3
France,17,3,68,8,479,324,2931,1400,97,7
England,28,15,77,7,458,364,3631,1301,73,7
Brazil,9,9,95,8,429,220,2677,1057,52,5
Belgium,35,9,98,11,496,293,3492,1192,100,7
Croatia,39,11,103,20,577,392,3708,1601,114,7

In [79]:
data_np = np.array()

KeyError: 'id'

In [74]:
a

{'id': 70, 'idx': 24}

In [76]:
team_stats[9598]

{}

In [77]:
team_stats[9598] + {'id':35, 'idx':12}

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'